//
//  CostViewController.swift
//  Myfinan
//
//  Created tambanco 🥳 on 29.03.2022.
//
//  Template generated by Tambanco
//

import UIKit

class CostViewController: UIViewController {

	var presenter: CostPresenterProtocol!

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

// MARK: - Binding
extension CostViewController: CostViewProtocol {
    
}
