//
//  CostViewController.swift
//  Myfinan
//
//  Created tambanco 🥳 on 29.03.2022.
//
//  Template generated by Tambanco
//

import UIKit
import CoreData

class CostViewController: UITableViewController {
    // MARK: - Properties
	var presenter: CostPresenterProtocol!
    var cost: [Cost] = []

    // MARK: - App life cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        self.presenter.showCost()
        self.presenter.showTitle()
        self.setupTableView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.presenter.showAddButton()
        setupNavBar()
    }
    
    // MARK: - TableView
    func setupTableView() {
        tableView = UITableView(frame: CGRect(x: 0, y: 0, width: self.view.frame.width, height: self.view.frame.height))
        tableView.dataSource = self
        tableView.delegate = self
        tableView.register(CostCell.self, forCellReuseIdentifier: CostCell.reuseId)
        tableView.rowHeight = 120
        tableView.separatorStyle = .none
    }
    
    // MARK: - Setup NavigationBar
    func setupNavBar() {
        self.navigationController?.navigationBar.prefersLargeTitles = false
    }
}

// MARK: - Binding
extension CostViewController: CostViewProtocol {
    func setTitle(title: String?) {
        self.title = title
    }
    
    func setCost(cost: [Cost]) {
        self.cost = cost
        tableView.reloadData()
    }
    
    func configureAddButton(addNewCost: UIBarButtonItem) {
        self.navigationItem.rightBarButtonItem = addNewCost
    }
    
    func presentCostVC(viewControllerToPresent: UIViewController) {
        self.present(viewControllerToPresent, animated: true)
    }
}
