//
//  CostPresenter.swift
//  Myfinan
//
//  Created tambanco 🥳 on 29.03.2022.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol CostViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol CostPresenterProtocol: AnyObject {
    init(view: CostViewProtocol, model:  CostModel)

}

class CostPresenter: CostPresenterProtocol {

    weak var view: CostViewProtocol?
    var model: CostModel
    
    // Enter buisness logic here
    
    required init(view: CostViewProtocol, model: CostModel) {
        self.view = view
        self.model = model
    }
}
