//
//  CategoriesPresenter.swift
//  Myfinan
//
//  Created tambanco 🥳 on 21.03.2022.
//
//  Template generated by Tambanco
//

import Foundation
import UIKit

// MARK: Output protocol
protocol CategoriesViewProtocol: AnyObject {
    func setCategories(categories: [String])
    func configureNavigationBar(largeTitleColor: UIColor, backgoundColor: UIColor, tintColor: UIColor, title: String, preferredLargeTitle: Bool)
    func configureAddButton(addButton: UIBarButtonItem)
    func present(viewControllerToPresent: UIViewController)
}

// MARK: Input protocol
protocol CategoriesPresenterProtocol: AnyObject {
    init(view: CategoriesViewProtocol, model:  CategoriesModel)
    func showCategories()
    func showNavigationBar()
    func showAddButton()
}

class CategoriesPresenter: CategoriesPresenterProtocol {
    
    
    weak var view: CategoriesViewProtocol?
    var model: CategoriesModel
    
    func showAddButton() {
        let addItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(addCategory))
        self.view?.configureAddButton(addButton: addItem)
    }
    
    @objc func addCategory() {
        
        var categoryTextField = UITextField()
        let alert = UIAlertController(title: "Добавьте новую категорию", message: "", preferredStyle: .alert)
        alert.addTextField { alertTextField in
                    alertTextField.placeholder = "Введите категорию"
            categoryTextField = alertTextField
        }
        let action = UIAlertAction(title: "Добавить", style: .default) { action in
            
            self.model.category.append(categoryTextField.text ?? "999")
            self.view?.setCategories(categories: self.model.category)
        }
        alert.addAction(UIAlertAction(title: "Отмена", style: .cancel, handler: nil))
        alert.addAction(action)
        self.view?.present(viewControllerToPresent: alert)
    }
    
    func showCategories() {
        self.view?.setCategories(categories: model.category)
    }
    
    func showNavigationBar() {
        self.view?.configureNavigationBar(largeTitleColor: .black, backgoundColor: .systemCyan, tintColor: .black, title: "Категории", preferredLargeTitle: true)
    }
    
    required init(view: CategoriesViewProtocol, model: CategoriesModel) {
        self.view = view
        self.model = model
    }
}
