//
//  CategoriesPresenter.swift
//  Myfinan
//
//  Created tambanco 🥳 on 21.03.2022.
//
//  Template generated by Tambanco
//

import Foundation
import UIKit
import CoreData

// MARK: Output protocol
protocol CategoriesViewProtocol: AnyObject {
    func setCategories(categories: [Categories])
    func configureNavigationBar(largeTitleColor: UIColor, backgoundColor: UIColor, tintColor: UIColor, title: String, preferredLargeTitle: Bool)
    func configureAddButton(addButton: UIBarButtonItem)
    func present(viewControllerToPresent: UIViewController)
}

// MARK: Input protocol
protocol CategoriesPresenterProtocol: AnyObject {
    init(view: CategoriesViewProtocol, model:  CategoriesModel)
    func showCategories()
    func showNavigationBar()
    func showAddButton()
}

class CategoriesPresenter: CategoriesPresenterProtocol {
    
    
    weak var view: CategoriesViewProtocol?
    var model: CategoriesModel
    
    func showAddButton() {
        let addItem = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(addCategory))
        self.view?.configureAddButton(addButton: addItem)
    }
    
    @objc func addCategory() {
        
        var categoryTextField = UITextField()
        let alert = UIAlertController(title: "Добавьте новую категорию", message: "", preferredStyle: .alert)
        alert.addTextField { alertTextField in
            alertTextField.placeholder = "Введите категорию"
            categoryTextField = alertTextField
        }
        let action = UIAlertAction(title: "Добавить", style: .default) { action in
            var categories = [Categories]()
            let context = CoreDataManager.sharedManager.persistentContainer.viewContext
            let newCategory = Categories(context: context)
            newCategory.category = categoryTextField.text ?? "999"
            categories.append(newCategory)
            CoreDataManager.sharedManager.saveContext()
            self.view?.setCategories(categories: categories)
        }
        alert.addAction(UIAlertAction(title: "Отмена", style: .cancel, handler: nil))
        alert.addAction(action)
        self.view?.present(viewControllerToPresent: alert)
    }
    
    func showCategories() {
        var categories = [Categories]()
        let context = CoreDataManager.sharedManager.persistentContainer.viewContext
        let request: NSFetchRequest<Categories> = Categories.fetchRequest()
            do {
                categories = try context.fetch(request)
            } catch {
                print("Error fetching request \(error.localizedDescription)")
            }
        self.view?.setCategories(categories: categories)
    }
    
    func showNavigationBar() {
        self.view?.configureNavigationBar(largeTitleColor: .black, backgoundColor: .systemCyan, tintColor: .black, title: "Категории", preferredLargeTitle: true)
    }
    
    required init(view: CategoriesViewProtocol, model: CategoriesModel) {
        self.view = view
        self.model = model
    }
}
