//
//  CategoriesViewController.swift
//  Myfinan
//
//  Created tambanco 🥳 on 21.03.2022.
//
//  Template generated by Tambanco
//

import UIKit

class CategoriesViewController: UIViewController {

	var presenter: CategoriesPresenterProtocol!
    @IBOutlet weak var categoriesTableView: UITableView!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

// MARK: - Binding
extension CategoriesViewController: CategoriesViewProtocol {
    
}
