//
//  CostModel.swift
//  Myfinan
//
//  Created tambanco 🥳 on 29.03.2022.
//
//  Template generated by Tambanco
//

import Foundation

struct CostModel {
    var time: String
    var cost: String
    var comment: String?
}
